//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        public int PlatilloID { get; set; }
        public string Nombre { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> IDESTADO { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
